version: '3'

services:
  tailscaled:
    image: tailscale/tailscale
    # start tailscale daemon
    # launch with the provided auth key
    # wait for the daemon to exit
    command: ['sh', '-c', 'tailscaled & pid=$$!; tailscale up --auth-key=${TAILSCALE_AUTH_KEY}; wait $$pid']
    network_mode: host
    privileged: true
    volumes:
    - /var/lib:/var/lib
    - /dev/net/tun:/dev/net/tun
