version: '3'

services:
  tailscaled:
    command: tailscaled
    image: tailscale/tailscale
    network_mode: host
    privileged: true
    volumes:
    - /var/lib:/var/lib
    - /dev/net/tun:/dev/net/tun
    env_file:
    - .env
